---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cronjob.yaml
  - ./serviceaccount.yaml
  - ./prometheusrule.yaml
configMapGenerator:
  - name: kanidm-client-reconciler-script
    files:
      - reconcile.py=./resources/reconcile.py
  - name: kanidm-client-reconciler-config
    files:
      - registry.json=./resources/registry.json
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
