# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-token-secret
type: Opaque
stringData:
  CF_API_TOKEN: ENC[AES256_GCM,data:9ZnO6Nc+nqllBY0XEv6VnkzeLNxbo+ho1x8flhJvzACOz3wtuT0hDg==,iv:96myUNIJPPtCUnkoNxHHqQduvQ9mWU1UIXZIoM/OGao=,tag:3Inm3xGHfL4tQ9EEUhl+5w==,type:str]
sops:
  age:
    - recipient: age1rl8s5e3al83x28ecwpn7ed3773uvyuhhvqujc47dz4chpw7xvc6qlzd8hq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcDlwVGgrN2NERW15dTJh
        Yi9hYkpIaHhrYzFpQmx0VFpJUnJzaXdjeHk0CmFqeEk5TGsxVUhjUitQeG1LTmdM
        RHRub3p4cmFxVkVmaWtGakF0b1V0NVkKLS0tIFhjY0lERWZ3bXh0ZjBGUTV5KytX
        cUd0WHFzOHhXajRSc1FpQmlDallObEkKlvjVYEtm3FpCgkBEaNX4Ifd7e/zc0BsF
        4ER8UmXKvORRdtX0/kjDFbaa/7rp5o2QmsxUzt6QKjQDYUx+UfQTfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-02T20:53:51Z"
  mac: ENC[AES256_GCM,data:sdKJo0hGssXvmAIxls3q4GoP9Vmn129ac4VXp3LpegT6oA9Uj683ImaDjxQUuNXHWccuukssDZPGEezTqry0G02DeVXWjdl49/UUXJdCj9tWfIu/0Mlpc5bvshc6xKgsabobsUnDhNUlUIDMF20DOF9+6IZ7cxMtw9DWDdinnnU=,iv:RY2G9dILnYHxI94LyBcgia6qygqCga/0z/MXrwoXYQg=,tag:Ov5Ab1Ag410VDChK+jqTdg==,type:str]
  encrypted_regex: ^(username|password|user|pass|secret|token|ca|data|stringData)$
  version: 3.12.0
