---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - httproute.yaml
configMapGenerator:
  - name: capacitor-gatus-ep
    files:
      - gatus-config.yaml
    options:
      labels:
        gatus.io/enabled: "true"
generatorOptions:
  disableNameSuffixHash: true
