apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cloudflare-secret
stringData:
  cloudflare_api_token: ENC[AES256_GCM,data:13sP9Lwr9o2YYA==,iv:4Sz4Hz+A/i833sp2ZsRf5mdh/nMy5dY/jNkJ/MP0DeY=,tag:nJGFL3CIlvmOg/ai0iiMrA==,type:str]
  cloudflare_account_id: ENC[AES256_GCM,data:sBTjAmgg24aIjw==,iv:8JKARyevCgQfGFk105lSwR/Hi4J6EeSRfewMMnQLBWE=,tag:DprdMjIsKKgQlgL/2jVIuQ==,type:str]
  bucket: ENC[AES256_GCM,data:tI9apSO8k5V9zw==,iv:Ma900qhKCPoFtXZQH5A5W03WxvNRlQwWHUcryZh84VM=,tag:Y8QDYygD07wWedkUJC0lDQ==,type:str]
  access_key: ENC[AES256_GCM,data:RwrnKyiRtnZJYg==,iv:m9l4LCIE05jR5fecMJcbuAm5Bk3uSewW9vskK3ze1Dw=,tag:rnHTQ0NL40zMfl75X4Mmsg==,type:str]
  secret_key: ENC[AES256_GCM,data:/RGxIlJx1th4Dw==,iv:Bb8OD8CKrdOQizi0y/8rBBiXkTr7ZgLjUpBeezRuuLc=,tag:qntWRaoOAYwlm7TB19Oxfw==,type:str]
  state_passphrase: ENC[AES256_GCM,data:+GiZsN9PWHNUpg==,iv:TCTEKC0D84/vT5+OXUt4BTdjAZXjLPUqxVsxDK0O78M=,tag:ypYGpaMcFnyIaCCC7dexUA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV2d5K0wzd2liZktCUExl
        WDZCWjAyZWk2MVg1Vk5ZdFBVSHQ0NnZkekUwClhHNjIwVUx5ajdvSW5tVlJIVlAz
        RStpQUh5azNLRG5oQ2hLYllQTmwrMUUKLS0tIDFlTXoyOE16blZMWjc0cnZwbE05
        eEZJeFdjMmNuMWpidGdyOHhlV0V4Y0EKaV2mO1Ea6p8viPSKqM/jAMh8RR9bHebT
        wkNNP3lfL4OtOD0oCMD+emqcjHxVFGmi1VtJctFPVC+uq1uQqqZxGw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rl8s5e3al83x28ecwpn7ed3773uvyuhhvqujc47dz4chpw7xvc6qlzd8hq
  encrypted_regex: ^(username|password|user|pass|secret|token|ca|data|stringData)$
  lastmodified: "2026-10-06T23:20:07Z"
  mac: ENC[AES256_GCM,data:MRt2+o7ThvuduRhoo3RMFLnVpD9HEoKLLemCP1KFDgu0ITZX9yGd1DZ3CtqC5Mwaubq8gEblBI9EOfnZFVDvcDnEJf7HLN+C16vwCffK/x3HNz15oLsMY+Rz6SrtHKHW/B0ePo3VHPQiESP9CwkT6buw8J3ImJHYaDkZn6m6r9E=,iv:0ARbG2Hs17vEwsM9K+ZZ1F7y+CKSEZS4p9e8QD4LQug=,tag:PgCJ4pcvx8/YS1M8UXWm/Q==,type:str]
  version: 3.13.3
