apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cloudflare-secret
stringData:
  cloudflare_api_token: ENC[AES256_GCM,data:RxhhZ2J6Qu4ROaSJ727aJNAXruPd8/OJb8FPSTWBVlObFtSLmaNUTyGjsBw7ko4KDfCgAO8=,iv:7Qh8dmI0xbe5cztFdcCUoy+mXranrNx4eAwC0u4h5vA=,tag:7YXSL55YjNtDIvEwlxAVnw==,type:str]
  cloudflare_account_id: ENC[AES256_GCM,data:IhTEuhkD6dZ3tDwKXhrGNHw60QZ39faqk8GeeftVkTY=,iv:vAzX0nUGYOb1N7YtaLzMBFDk/KxaPZ8waZppVwIXX/8=,tag:Ib0y3Aazs9kciZn5OV3Trw==,type:str]
  bucket: ENC[AES256_GCM,data:+f0Xmzkmmbw0ryfVyPOl9clG2VFVRpcPrO4+OignpBjlvoaPRCA=,iv:SaK0M3sPUHxDd3QLKRa5Brf3qKW7BP+DmtwH7aEBuGg=,tag:EmoXkZWVvBlSLFGqQFbHJA==,type:str]
  access_key: ENC[AES256_GCM,data:uZOlfHTzd1qD2eNdRfkaJBywuYkSf4RrkA==,iv:w+yGJUuEAY8AxKGYovDmqPqfwBSpnUr7VxLbuLu43P4=,tag:AfOgaoIVr4ZdZ6Xj+yg5Tw==,type:str]
  secret_key: ENC[AES256_GCM,data:zm9VtldeRFk2relq2MG95ac1DMtFxaMDlhtuXR2YNw==,iv:IPwanV8+x9cdYF/uxkJwLEmuyAvKmAWkjEQV8yKkpFI=,tag:wTrYMaNClyfSRJHKg7XEVg==,type:str]
  state_passphrase: ENC[AES256_GCM,data:5/rrrBse9lYVIhf9I8WqtWh6380rBbSUUncVjv+sEmsP9q1pJxQYYBp3e1U=,iv:YGlPBmiBNKnxzyLjwMtNzzfOBNJexgCRJNUWqBNaACw=,tag:PSlxk++8kNPj2cml1bDLiQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VE9lSGQvb0FrV3VjVm9H
        YncySG1PL2pCT0lhQVB5SWxhVnhZbkc4eWpnCmwyZGRmU01oTmxhQVNrUW4veXZu
        dmdVNlJrUkl0S3g5NmQ0ck83U2N5ZmMKLS0tIEo3eWVyNU10S1lyODBrM201UVVR
        MlF3M3N5eE15SU1jbnN3Y1VTOW9WdWcKlaOTShUhgUVoCwvVfEuFCCdINPRu5DES
        3QMgqh9F2XMHrvWjdqoMonwfSseUr0OdYBlPyTAghMXkX+h7fbOUIg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rl8s5e3al83x28ecwpn7ed3773uvyuhhvqujc47dz4chpw7xvc6qlzd8hq
  encrypted_regex: ^(username|password|user|pass|secret|token|ca|data|stringData)$
  lastmodified: "2026-10-06T23:32:09Z"
  mac: ENC[AES256_GCM,data:rnk9/LFodw3AgSY3eyE0LCyjTVnS5r0ofcHohqSHcSoZZ+ONKfo9tvJYLt/T4jrrnnCRa+Xxi9cZR4x3I3JdMxQLFw8GnVlyktZqmQwCpHJVGVRjz9Iof2ERrMAcd+POR6O6Hq30xADiLP6fzEypstHZmgG/eMy7RTJiZXniKcI=,iv:wIj018KtOqOrZPj/J69/SrHurKmSOgNbLaXCoVcoLqU=,tag:l1ncsAZDeg4s3aeE5thfKA==,type:str]
  version: 3.13.3
