# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: wunbot-secret
type: Opaque
stringData:
  DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:tx1stONtWtZPn+4r6NEDrsHIBUbRZk96rWqKjhBjhVfV5RisamrfDmQF9dNegsD3BMefF4540NwVswAjUGSafhX7ixDUQg==,iv:4BAdr1S/13MouErB7xrkDvVGV98NgH/+hSeY8QSEQqA=,tag:yf9c7UMNNyD4SfVAF3BRLw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiY3l1VVc3YkpPMkF5S05S
        cVNqelFwT1JvazZSWVNKUlpoS0RrSjZaVmowCld2U3ZUbDl1Y3BjalVzcXUzUUE5
        bnU3QXFYcEF1M3dyNzlRS3JLdWVGMzQKLS0tIE85VWh1cFNVeUxNUXhwOVArcmlL
        dEJxV1dIZmg1UWpEbkFxd0ZmT0hUSU0KpE4zORB8wXTzDRKQTUigFYwAvehjEiYc
        BT04zCSmBRW7NFfflSGyWLVYSUqBFIgxdlbLgmDqM05yrU1uqrQmBQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rl8s5e3al83x28ecwpn7ed3773uvyuhhvqujc47dz4chpw7xvc6qlzd8hq
  encrypted_regex: ^(username|password|user|pass|secret|token|ca|data|stringData)$
  lastmodified: "2026-09-07T08:39:35Z"
  mac: ENC[AES256_GCM,data:ixPteWtvEM4NvAHJQefl0tbQIbJ7DWEjjY1VVmmyMEC8uhmqwJsQAZaK8Qqkj3IGVPL0vZ1s04Fg66xnERk9iT0OICwQ3KNmTJKar3Juw85GUTvLBm0tth1QyIDxXv+yY6pd+ul/IDOm8v0ZcczGzUgWhAQwCxeUehvH/pPP0nI=,iv:AOmFdFYCUwoI8ji6XuEEykbHuWeCrSbIix/jzYBhPZE=,tag:LHC5LV1sHrG3bZQsScE6JQ==,type:str]
  version: 3.13.3
