apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cloudflare-access-secret
stringData:
  cloudflare_api_token: ENC[AES256_GCM,data:nF0TCU/p2qCU3Q==,iv:YQyrAcEiz5j6veerARD6014UsoOsHBcs5T0bvvFCSVc=,tag:vjO8gOOv01zQyhY+cnxc8w==,type:str]
  cloudflare_account_id: ENC[AES256_GCM,data:adzhypO0Ef8w6g==,iv:Y8F57OtJNPcVwEUTv7sf45Qmm67iuh0z5MfCTbzx5Ks=,tag:fXTh4ZJi4DI7exoQh2T0/A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUnA0UlVVVi9qT2ljcm5x
        ZExKbk53VjRFSzg2UkFraitGWlNaS0ZiOFg0CnladkdCZEQwVmxWNEh0eUt3M3Ry
        RjBXbEJrSi9QcXNmQlBzZE5FdjBJM0UKLS0tIGJJS1RHRys4Sm4wUFZkNU9SeE5N
        cFdqUVRsY2FSbEF6RmxHdDN3c1V1b2sK8PTz++jNS0zZM6Lq8pFmZ3UDhccXL4Zq
        +mhBjU/6xK03S1R627vl02MrHapcu4XcGsBBGaI0V1cdVBAWbHVfCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rl8s5e3al83x28ecwpn7ed3773uvyuhhvqujc47dz4chpw7xvc6qlzd8hq
  encrypted_regex: ^(username|password|user|pass|secret|token|ca|data|stringData)$
  lastmodified: "2026-10-06T22:07:08Z"
  mac: ENC[AES256_GCM,data:Rnjl3+u/74mmGPZghYCCJ90f1HSSYRmprvmLGLpK0n8qnigmAbl+fHZIKO3dLecBjjABepk1X1nPTFxW74IjYyHkShDTsbATildfRzluN+wUC28ffOfa/btmM5dkdZWjFljOmPHigozPty53LaxKEVdu+tk1hQfE8wUvT8o8Bkw=,iv:RjewOa3LkIOKkMweSmb6KHeHZk+YUjyWYVkifcbIgp8=,tag:RDVz4H6gzFuIPSP8VQS1Nw==,type:str]
  version: 3.13.3
