# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: observability
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:BeE3vy8TDX0=,iv:GdvJvKTPOv33m3rRWVKkKSSny4N7KFE0VXQ4Iem1i5c=,tag:QMHwYHyAvfScD+koFWTLNw==,type:str]
  admin-password: ENC[AES256_GCM,data:MaRQR1N6498JpLHQ/A==,iv:QbJDuQWYDJcb3swWE2tHCu3hyQUB/Nl35NFQzk4P3nU=,tag:g63I3+jEsZ1wUwG+F43FRA==,type:str]
  oauth-client-secret: ENC[AES256_GCM,data:FXdWsI0xl5rRf6WMO4n5F0ce0nvmvNtB8xQ5tqyxDEFZ2g1A3EmvnM80Pn4s8QiH,iv:3xR8Z6PlA0JJ9CUPTS8gMWr+86PgT9FEk2BdAJQTiKw=,tag:rkh2z7+4MoZ8rn8jpTPrzg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aDF2RC96Qk5XNkxBUVpx
        U1V0NlNIY3NUWmhDcW1mTEZaREhXTVlnNzJNCkF5d0d4ZmxsSndDUzRXZXVocUZ6
        Yy9EMW9oK0daN1RMYUdmK2UvckI0WFUKLS0tIGxoZWtEbnJxbVdOakgyazg4U0dz
        UjdOSU1Ta2FQUWw3VEFwQm9hVWJWbUUKvjj8QMNdR4uLtLzDEIcwefGtKWME0nxY
        p38SX0Wt5w0hnegbvqpGIHK/Xxa6FWQitP4QxIaD8ryNoetoas5TZQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rl8s5e3al83x28ecwpn7ed3773uvyuhhvqujc47dz4chpw7xvc6qlzd8hq
  encrypted_regex: ^(username|password|user|pass|secret|token|ca|data|stringData)$
  lastmodified: "2026-08-12T01:06:15Z"
  mac: ENC[AES256_GCM,data:FYn49Sb8XkRnskqEH7bVT1L9f1taIScAtLL4A19shQZEgJUUGdRQ49jfHhkJ+yIdnrmqYCCUV8PBm0xIJz8SeLm991ZK+vlPmDA9+WLIS/usn3bnLZchF4i+ft/niKl4x+4hJMAhsdcB/I6FNH+BYrwvLHiNkWZb5zaNKlkBAWc=,iv:9pgP3S9cg6Omn1z/rETcGcmL5d1FEf7wxTRLXqjlPX8=,tag:20mPeBbFcx8M2YoSMsIJZw==,type:str]
  version: 3.13.3
