apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
  namespace: flux-system
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:wNoHYf7+CKlp375mgzUPjiS0/Mg3Ru/RvAwKkXD4ZnMVvE/Rm4KvJbbRlPVTXFNYzDQodhtgIDtEizwEQmJBSw==,iv:oQsw84nw7NWDedrM9Zem9Qd2zN3P27GbsIkmt0GuLk8=,tag:O69keVn/fJMBcWmtiUm86A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMjNhU0FGZWZwSGEvcko4
        TTgwb3Q0MWxDdkZIVnhDZzRoNExydlhnR3p3ClRtQlFlUjhXaGNoczJOWmpXUG9n
        TnZQeTIyWkxXdGJaZDI5N0dXY1did3cKLS0tIHdobmcwbXB1R2V6SG81RGdDYkpw
        M2FwTEFMRWIwREdPd3VJQzg5Yzg4QUkKBQ6X3go7iT58Pxo/HwAU5UX0k4+C5+b0
        yqrJuoFC99FLv3Nlm1RDLYx6QYa1nlmxdOsovrIMCXYxgbLqkSFmVQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rl8s5e3al83x28ecwpn7ed3773uvyuhhvqujc47dz4chpw7xvc6qlzd8hq
  encrypted_regex: ^(username|password|user|pass|secret|token|ca|data|stringData)$
  lastmodified: "2026-10-08T18:43:05Z"
  mac: ENC[AES256_GCM,data:euSYFK15ZM2ixV7aWNZhfr24GCVZvm8t41puTNxC9ut3Gx0radmDsBH41yo9z1A5IAjxV/EdXOD9n4kfZpMrCSIERARW6qj2YYKybZb1aaZKh+3wPst4V2nrTBJJ4mAaDXaIvX9413JqS4knBkgfm+CQ+53PLeaqKPaSUzqQlWo=,iv:+jOsPdWep50TaPqk98WnU5oHEQWnz1N1wO+QwI9S320=,tag:5DREY9qKmFdDjREpGSJNeQ==,type:str]
  version: 3.13.3
