---
credentials-file: /etc/cloudflared/credentials.json
ingress:
  - hostname: "*.chancey.dev"
    service: https://envoy-external.network.svc.cluster.local
    originRequest:
      http2Origin: true
      originServerName: external.chancey.dev
  - service: http_status:404
