---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: flux-operator
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    serviceMonitor:
      create: true
    web:
      enabled: true
      config:
        baseURL: https://flux.chancey.dev
      httpRoute:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: flux.chancey.dev
        parentRefs:
          - name: internal
            kind: Gateway
            namespace: kube-system
            sectionName: https
        hostnames:
          - flux.chancey.dev
      networkPolicy:
        create: false
