apiVersion: v1
kind: Secret
metadata:
  name: flux-operator-oidc-client
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:jV7byccGAf1vfPzljHbYnXHzEO4EiQwudjRwHZ8bGPtXqM1Ay7wqs7vHryOrObB9,iv:pTcytiKcNN0/3GgA1bmkelAc8G9F0fZ9lmYkVoBY3J8=,tag:afo6+taDMnEZIrMB9Rb6TQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWTdNb2NBQVQxSjI3bzJj
        NDdzQVk3bGNFb1N1MHlxTEFKdWtrYTdjTmhvCkRVSzhBR0YwSWpLakk1VUJ1dXRB
        elRMakViVVNHYVZMcGRJMEtlWVF0T0kKLS0tIFY1d3NsNmtXZHBhNlcwbXhRZEJI
        V29JSit0VXlmSFBIZ1ZFTFoyOXZUR00KfrFY9aqOKRpIpkp5TK3BPo/iSHXbaKr6
        KZa5R8K+WoQgXxMZQHPCASq1n9CSh5c+Fa4rTjzs2BnB45dY5j70Sw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rl8s5e3al83x28ecwpn7ed3773uvyuhhvqujc47dz4chpw7xvc6qlzd8hq
  encrypted_regex: ^(username|password|user|pass|secret|token|ca|data|stringData)$
  lastmodified: "2026-08-12T01:18:15Z"
  mac: ENC[AES256_GCM,data:AkbyUOiotrwIWh6rEGauxWRB6cA0hJSMmk0w3ocljTd/5QtIeVM6iRpTMnUOAJsR2+itaUYENHjD4Oozhix2o8a6AXyohw567vDTFQC9mi4tdwrsFGvVzg8X7Pdcvlo1QVGomb/x7u84YarUCAUtBH9RUZOu6pSIIbyfivPIu8g=,iv:QrL/Oe4tWSDGlXGHR4Kz3ResInbfoRD/ZE2k3r9xEKg=,tag:9cyb2FV5gSV2bygh4STlQg==,type:str]
  version: 3.13.3
