---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: chancey.dev
    target: _self
    background:
      image: https://i.imgur.com/NdsEGXR.png
      blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 30 # 0-100
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github | stacks:
            - abbr: GH
              href: https://github.com/jonathanchancey/stacks
        - Claude:
            - abbr: CLA
              href: https://claude.ai/chats/
        - Google Cloud:
            - abbr: GCP
              href: https://console.cloud.google.com/
    - Personal:
        - Kagi:
            - abbr: K
              href: https://kagi.com/
        - Wanikani:
            - abbr: WA
              href: https://wanikani.com/dashboard
        - Monarch:
            - abbr: MON
              href: https://monarch.com/dashboard
        - Spotify:
            - abbr: SPO
              href: https://spotify.com/
    - Professional:
        - Email:
            - abbr: MA
              href: https://mail.proton.me/u/0/inbox
        - Calendar:
            - abbr: CAL
              href: https://calendar.proton.me/u/0
        - Prusa Connect:
            - abbr: PRU
              href: https://connect.prusa3d.com
        - Onshape:
            - abbr: ONS
              href: https://cad.onshape.com/documents
  services.yaml: |
    - Services:
      - Immich:
          href: https://photos.chancey.dev/
          icon: immich.png
          description: Photos
      - Forge:
          href: https://forge.chancey.dev/
          icon: forgejo.png
          description: Version Control
      - Home Assistant:
          href: https://home-assistant.chancey.dev
          icon: home-assistant.png
          description: Home Automation
      - Miniflux:
          href: https://miniflux.chancey.dev/
          icon: miniflux.png
          description: RSS Reader
    - Manage:
      - Proxmox:
          href: https://proxmox.chancey.dev
          icon: proxmox.png
          description: Hypervisor
      - TrueNAS:
          href: https://vents.chancey.dev
          icon: si-truenas-#0095D5
          description: Baremetal Storage
      - Kanidm:
          href: https://idm.chancey.dev/
          icon: kanidm.png
          description: Identity Provider
      - ZITADEL:
          href: https://auth.chancey.dev/
          icon: zitadel.png
          description: Identity Provider
    - Monitoring:
      - Grafana:
          href: https://grafana.bastille.chancey.dev/
          icon: grafana.png
          description: Observability
      - Gatus:
          href: https://status.bastille.chancey.dev/
          icon: mdi-gate-#3cad4b
          description: Up/Down
      - Prometheus:
          href: https://prometheus.chancey.dev/
          icon: prometheus.png
          description: Time Series Database
    - Storage:
      - Garage:
          href: https://garage.vents.chancey.dev/
          icon: garage.png
          description: S3 storage
      - Kopia:
          href: https://kopia.chancey.dev/
          icon: si-kubernetes-#326CE5
          description: PVC Backup
    - Network:
      - Unifi Dream Machine:
          href: https://intrepid.chancey.dev
          icon: unifi.png
          description: Unforbidden Router
      - Hubble:
          href: https://hubble.chancey.dev
          icon: cilium.png
          description: eBPF Visibility
      - Nginx:
          href: https://nginx.vents.chancey.dev/
          icon: nginx.png
          description: Decoupled Reverse Proxy

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: custom
        url: https://kagi.com/search?q=
        target: _blank
        suggestionUrl: https://kagi.com/api/autosuggest?q= # Optional
        showSearchSuggestions: true # Optional
  docker.yaml: ""
