apiVersion: v1
kind: Secret
metadata:
  name: prometheus-oidc-client
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:SNJXR9XPvhtaXv1gWPvYeksqRVPKlr632vqfPX+mbuUsy/EyrqX5TE2rETKH82nh,iv:1bSTrHHARCDC7dpYFevV21HPHs4Gneb53Pm7XKsVTog=,tag:bY0syn2P0ozlS2E1zJSgNQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFd3U3d0ZPWmc4UVZSN2xO
        UmRLNkV6dFYrQWRJN25UTFJXOU43ZFJCNUV3CmFVZ3ZOSDlPNlMrTnc4SzB5TWZJ
        Y3ZHb21hZmk5TWprTERZbzR1eXBGYjQKLS0tIGF1VS9kYnpHdTI4V09jeHkzNEZN
        V1h2eGxrcm80aFh3eUFVQWlBUjZnQ2cKrCZuZSOVqnmzUNn0xMzXt0tqqD9bYn8J
        k4a7ybgIyGiUAsmcmuD8u7i8yuia6gQv0LlfAehfYobgCda+VflrFg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rl8s5e3al83x28ecwpn7ed3773uvyuhhvqujc47dz4chpw7xvc6qlzd8hq
  encrypted_regex: ^(username|password|user|pass|secret|token|ca|data|stringData)$
  lastmodified: "2026-08-12T00:45:10Z"
  mac: ENC[AES256_GCM,data:OpZ0nIocqAvcOYjJnUmZW/+MpWONXP1EnbRJs4Fzt3bTOtxwLkpZNJ+CHEWXfH8xtxQ8wSKBdDu1p+X6NMKO4ShAOty6VN0QewgagKL2r5pc6dOr1QHGRPlzN18Sh96ASKKmiXfSC/PNmeRTVqqrvgdTQoMD+2iejp6B96QjJ0Q=,iv:xfRK/1uTLNi20lzoVHMe9w9Wc7qrIAS9TZI+9ndqulE=,tag:FwHOgjncPezsbnqO7FspPg==,type:str]
  version: 3.13.3
