---
endpoints:
  - name: "${APP}"
    url: "https://${GATUS_SUBDOMAIN:=${APP}}.${GATUS_DOMAIN:=chancey.dev}${GATUS_PATH:=/}"
    interval: 1m
    conditions:
      - "[STATUS] == ${GATUS_STATUS:=200}"
