apiVersion: v1
kind: Secret
metadata:
  name: kopia-oidc-client
  namespace: storage
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:t80pRD3x0x6rMLHRC6ISzS4I0IMzaHLaih88yqDpsDHCgCIvvJ8H31lpv3jcuZC3,iv:6C4TOvnPqIJP5mIVh0YXZ8gl1dlba4e3lz7Cm0aIrgo=,tag:MdkKhhBoAWC9dmm0xF9ZkA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UGlyQ202L2ExazhJeUNz
        c0EyZS9rY3M0ckFiVjA2bzd4K3FxWUoybHlFCnVwRFFYa2M1dTZOUWhKQnFRbEZS
        clFPdVB4OGhTakgyYjVkbGYwTlY5T00KLS0tIGthZXYxMFgvM2h2aHlTdXNJdGZF
        S3FRSDdkM1U1M0d0b3hhbFNxcUdISUEKtFhD52UZpi+V30X3vllONDRHjUoWlg73
        A+vywcnm0exlU/tNboKQLs8x4kI4+CsUVGNX9KGQM/vuAnqEKCybrw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rl8s5e3al83x28ecwpn7ed3773uvyuhhvqujc47dz4chpw7xvc6qlzd8hq
  encrypted_regex: ^(username|password|user|pass|secret|token|ca|data|stringData)$
  lastmodified: "2026-09-05T21:12:54Z"
  mac: ENC[AES256_GCM,data:b84Nt6D4dvFXT5FiXeJEkDiT+5AH1OePC5SkBFHmGttlJ5L7pNad+FvPmZ4WrP9RPC33InQwwdiNbDIl7TS8YrnTMkXk3DHWTReVqnOqqeNhk5J7Yomkix2W7LEWx2hwgM16m4wbkqmG2yU9iL/kZG2rxUrZV4LGv34zHZuNAws=,iv:MdgDdMmT5T2LCIp/jwdAylGYLryFKeQeMLzjPxouc0Y=,tag:Yf1GQyqQrcUNN5KLWbiKyA==,type:str]
  version: 3.13.3
