apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cloudflared-tunnel-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:gK+g76je0JQmjjVog5nVAU6IY5z3V8h8XRdOCQGaYwuLnY7w,iv:YL/CAzth0T1uuKexw3dSsGHon59HGEnqpz+wxJrmybY=,tag:rohPb6yOF27foRZrY7l8SA==,type:str]
sops:
  age:
    - recipient: age1rl8s5e3al83x28ecwpn7ed3773uvyuhhvqujc47dz4chpw7xvc6qlzd8hq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVldaTUlZcFZjdEkwY2l6
        ZkovRjluSEl3Tk9xYmwyV05YNmFUZWVLb3k4CnBGYjJhRGhHcjBnOEVOOTVzQThu
        aHBFeWpOcW5sUHJGd0QvWUNOc0VmYU0KLS0tIEl4VDROWVAybjd0ODViM1ZvbkF2
        dDNUTlZWVWN5dDFHaUhmSFJMNDU4cDAKRuV+d3Wrrsos4nhzMWJ8ZYu3UDmiFjSq
        1GNUyw3fcx8C2u4TTZ1FjfiRfgnC78LZ41RZ4DlU/nHqToqN1B6Lqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T23:27:22Z"
  mac: ENC[AES256_GCM,data:9okH7ypWIt+SKyzYdSkWZpA0MFS3CPGhPlVBcnPmsoFMhqqcgZxpM/yjrjhJXUkv8GqtqVvdcswW6lDh8HdJibJHNH0Ei/KvCBplPJ/8euc7OHX1t88lGY34fD2j2HCuxM8ql5v9ICjmWzeSPI8pUcSIr0lopa02ciJuqJNMILM=,iv:17I3Ib1Qw3bDfs9KDHhgLAVnfFp4hJVFgdhPbGQRz7M=,tag:9+uVVIG+6gM/JD+DE/DE1g==,type:str]
  encrypted_regex: ^(username|password|user|pass|secret|token|ca|data|stringData)$
  version: 3.12.0
