hostname intrepid
log syslog notifications
frr defaults traditional
router bgp 64512
 bgp router-id 10.131.128.1
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 bgp network import-check
 bgp graceful-restart

 ! bastille
 neighbor 10.131.128.10 remote-as 64516
 neighbor 10.131.128.11 remote-as 64516
 neighbor 10.131.128.12 remote-as 64516

 address-family ipv4 unicast
  redistribute connected

  ! bastille
  neighbor 10.131.128.10 activate
  neighbor 10.131.128.11 activate
  neighbor 10.131.128.12 activate

 exit-address-family
