---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: amp-orbs
  namespace: network
spec:
  endpoints:
    - dnsName: _amp-challenge.orbs.chancey.dev
      recordType: TXT
      targets:
        - amp-domain-verification=2f12ab4b3af34059bbf1f5143a6b0c0a19009ded584e4ce6871f5de8aa7b350e
    - dnsName: _acme-challenge_g7k2v6l6lx7vbw24.orbs.chancey.dev
      recordType: CNAME
      targets:
        - 67c6824c-32c8-4e7e-aa5a-b3f48a2f1ad1.1.authorize.certificatemanager.goog
    - dnsName: orbs.chancey.dev
      recordType: CNAME
      targets:
        - custom-domain.ampcode.com
    - dnsName: "*.orbs.chancey.dev"
      recordType: CNAME
      targets:
        - custom-domain.ampcode.com
