module "maia" {
  source                       = "../../modules/proxmox-vm"
  name                         = "KIPP"
  description                  = "Managed by Terraform"
  tags                         = ["opensuse", "terraform"]
  node_name                    = "TARS"
  cloud_image_node_name        = "TARS"
  datastore_id                 = "local"
  cloud_image_datastore_id     = "local"
  vm_id                        = 103
  memory_dedicated             = 32768
  cpu_cores                    = 32
  disk_size                    = 30
  dns_domain                   = "local"
  dns_servers                  = ["10.10.0.3", "1.1.1.1"]
  ip_config_gateway            = "10.10.0.1"
  ip_config_ipv4               = "10.10.0.30/24"
  sshkeys                      = var.sshkeys
  username                     = var.username
  password                     = var.password
  reboot                       = false
  cloud_image_url              = "https://download.opensuse.org/tumbleweed/appliances/openSUSE-Tumbleweed-Minimal-VM.x86_64-Cloud.qcow2"
  cloud_image_file_name        = "openSUSE-Tumbleweed.img"
  cloud_image_checksum         = "e22d535c7580f633adc1e4e5599160ef45a8e9c8d868376c51af065a3d2a7578"
  virtual_environment_endpoint = var.virtual_environment_endpoint
  virtual_environment_password = var.virtual_environment_password
  virtual_environment_username = var.virtual_environment_username
  tpm_state_datastore_id = "local"
}