apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:q6NqT38B8y3IrmLXXh3k/QCFsQrzQ6qlzZHMaTIsOIyhg/m0v+shBlGpxamrrnuid2FF7eHQWPVqERnJxuKq4PsstO4EZYXGdcZxu8L2WsDD0UUY5jsCOmBCoWRKTI3GxAEqls5K46nsY1uCYDYXG2Mjo5KQs6cIy/lScoKPhQ0/JEWTy2NxTzvu,iv:HSulx51h7+OfOOvBgGH3smvQM31RpskRFjIF+Q6LV0Q=,tag:S4iP5f3lnPtQbbRHWs7H9A==,type:str]
sops:
  age:
    - recipient: age1rl8s5e3al83x28ecwpn7ed3773uvyuhhvqujc47dz4chpw7xvc6qlzd8hq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MmlMc1Q4eTZRbFBxOGhn
        ODZCdWFxOVZ1eGt5TUpsdnNDQ3krQ3o1SXpvCnlhQzVtclZxTE1xYnRxcmlmTzlr
        czcrSEt1MnBwRFVJdHJ1cEZpQ1pWZ1UKLS0tIGVDOFN1NlUwNnhlY2tSS1lUdU1p
        eEVOaVpPY3FQaW5OWGE0MS91RVJpK3cKiOJPhH8jZU0T+Er+8EP038o6/Ubd8gi3
        6pk68lwV546FZsEphxPFp3ETgFfcDm8FaEAlBK+zGxyBj4IfjBhfbQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T22:36:11Z"
  mac: ENC[AES256_GCM,data:ifOaQEXK5UWeU32IN/IU+669Y7Td2E9b1opIf6w0mWe8Nc59p++R6WCLImNi6+Flu8I/jE86dy/3Uohb1CHQ4l64y2dNujQ0YoRu40r7XrdApGANgUB14X2QF22B6xlaKA+Eojla3bH5d7JMGBSUh672z5+Z4tOYVxTESTeTJi0=,iv:q2ruvz7aPCuY5tOdLag3ftq/2oe1D0ELOZ6IaY0lnBY=,tag:7y+RREWad/vxpqYVUMtGHg==,type:str]
  encrypted_regex: ^(username|password|user|pass|secret|token|ca|data|stringData)$
  version: 3.12.0
