apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:cIpG6t/hqFY2jmCPNnM6rtMCLHMi9hS1MtNmEOOcy/2m9z0zyoUvX1bHU+IBSAOylpyuMkzG7XQVdlMlRQxzUOLnKWEwaGbWmnSGjgK/y+BF0t0ZnECnWmn+/7BUWOExIlmmtXEbYyXiRen2Yih4atWmjK4S2gm45XcqpCYR1+wJ8pYXPD888JcKamlp47tIGM+FMEU3wCerB5UHdrOK75Bb1pxo,iv:+/i3ij5cHFVIbaKZsuaySQkyxvakXOuDi+jGtdoIafE=,tag:j3uT/IcEmUjfeHTBERGVoA==,type:str]
sops:
  age:
    - recipient: age1rl8s5e3al83x28ecwpn7ed3773uvyuhhvqujc47dz4chpw7xvc6qlzd8hq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVjE3NkFNM0Z4YlR5bWhB
        NmVZclJtTUpXZUg4NU1UTUNaQnIzendqS1cwCmx3M3ptdWN0YnBwanFzTjJDN0Fy
        MmRycVBaUDc2Y0JCOUNsa3RacU5jcFEKLS0tIEY2aDNybFhlZmZGSHNNaGJPWUZv
        Wkk3WTgyUVhZZXpLMGhXWW9YKy9ORzAKKl1QHKOL3yz1t0Lf01O1KTbwBhlrm0Y1
        Uukj1pezdkSq7J9NQmEYKD002gVAWSvvTn4r/1MrEyucrh6+WjlZsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T21:48:41Z"
  mac: ENC[AES256_GCM,data:s95NcjJV8H0tnBizaiavE8FomIKPyokagqhxGcWaoc12XzLPFT/193XOVbs8u+2qCnF37Zk+OiByaEATgmmLQJ7TgIPUK27VLd0+Pos9qT4xEtV+B4Cs3sJ24dhI2aqMjpHiHorJcqel0Qgz8vxkL7G09/jzYeNXhGpAUFKppGQ=,iv:ecvZd+O4yzlsIEbWe2lf95ABLuJQko5Z3/FO/1QETlY=,tag:VKL66RSFhC24/tPHN/07Vw==,type:str]
  encrypted_regex: ^(username|password|user|pass|secret|token|ca|data|stringData)$
  version: 3.12.0
