apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:lxpdxuZXctbevFc2YishdCUrpvB0dQN0wfCBfLZ5sKSVnx2WsQ/OYdUigJSFXJUztQO7YO9oRDXGGXsKLRecyGNiUXeMiiB2Mn/VUPkGFx6vtC0e44hYwqLRMAzf24RR6yq6cZVIPZc4CfdscfcqBSmnYKSCqYwQNl/Kdsp1uvr2RRIo4LOvezismqACCQ/9Nn21n8X7XixTjGwsI9WKok1T5OJ2jM0j7sS7YDANwwTRsCPTfNEywQ==,iv:eGO/JSdJcvKPblE73T7Nn012YUg9m1gRqZ8NkEnKU3s=,tag:GofUODcs82Upi29DyUZrsg==,type:str]
  TUNNEL_ID: ENC[AES256_GCM,data:dZwHNP3PzFfHcEdHxXiy4Vb5/IRrGYx1MPu4oAe5h3OKHPqs,iv:e8LTMBf5xTF1Ifr3RWG5iKRB6539BVi/brlYy/gthY4=,tag:NDX9sOgvLeX6vUp+7sF0oQ==,type:str]
sops:
  age:
    - recipient: age1rl8s5e3al83x28ecwpn7ed3773uvyuhhvqujc47dz4chpw7xvc6qlzd8hq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbER2ZFJ1WUxYU2VJLzNC
        MXpuNEtIbDltTGdSTzJPUC81ZmsreWlwdndJCmNLaHV3ZHFvcWxDODI4UEpjc0tE
        MGN1cjRJcEF6VGhqVWxYS2RWdEpRczAKLS0tIENBczNLeGNHd1hNdW1ZdEV4WG9n
        Nm8wUjNpNXlET09PaWVET0NBYVo2aTQKg2f+6x0+vxs2lzLRW38ACxeMovEOGdBz
        qORSUZCaKChQrUepXcnmdp/GkUj1NSjVfs+FYrsCn5oqejDu7AtPZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T20:28:47Z"
  mac: ENC[AES256_GCM,data:CWLDOSG/kfUOgZ+ICb3ewvvMAqRm/j553RYMkTaN32qozrNyDYJ5GV4Uze3n+MVJPMQdkbYFpyFGRuiU/2eHtB7gE9XRpEK4GLrIR33aA3e/p/oaU7g29lt9WswecAfZdjhv6DHpOj8P2lhSaoiDaAQWqhZ4SsIozNNB8J1hW0s=,iv:bggmrj+YVKDnVpkPtNyQfw62JpkD9BquuGadwLduSp8=,tag:f+7GFoYo+Lcaz3svHeIYiA==,type:str]
  encrypted_regex: ^(username|password|user|pass|secret|token|ca|data|stringData)$
  version: 3.12.0
